### ISSUE TITLE
`publish = false` does not work

### ISSUE THREAD

**Issue by Blobson** [unbroken-dome/gradle-helm-plugin#14]
Here is my __build.gradle.kts__:
```gradle
plugins {
    id("org.unbroken-dome.helm") version "0.4.0"
    id("org.unbroken-dome.helm-publish") version "0.4.0"
}

helm {
  home.set(file("$buildDir/helm/home"))

  publishing {
    repositories {
      artifactory("my-repo") {
        url.set(uri("http://my-repo/helm-dev"))
      }
    }
  }

  charts {
    create("myChart") {
      chartName.set("my-chart")
      sourceDir.set(file("$projectDir/src/my-chart"))
      publish = false
    }
  }
}
```
Trying to run __helmPublish__ task fails with an error:
```gradle
Script compilation error:

  Line 21:             publish = false
                       ^ Unresolved reference: publish
```
Replacing with `publish.set(false)` does not help either.

**Comment by Blobson** [comment]
It seems that it does not work in Groovy version either, failing with an error:
```
Could not set unknown property 'publish' for object of type org.unbrokendome.gradle.plugins.helm.dsl.DefaultHelmChart.
```

**Comment by tkrullmann** [comment]
Hi,
thanks for the report and sorry for the long wait!
there are actually 2 issues causing this:

First, the convention that adds the new property was not installed properly -- it needs `convention.plugins.put()` instead of `convention.add` (I never really found out what "adding" a convention will effect). This should at least make the property available when using Groovy DSL.

Second, the Kotlin DSL cannot really deal with conventions yet, and not even with extensions if they're not installed on a "static" object under the project, but rather on a dynamically created object like `HelmChart`. To work around this, I created an extension property for `HelmChart`. It's in the `org.gradle.kotlin.dsl` package so that no extra import is needed in the build script. However, this comes at the cost that the property will now _always_ be available, regardless of whether the `helm-publish` plugin is applied or not (and it will produce an error if it's accessed without having the plugin applied).
