### ISSUE TITLE
How to run gradle build without helm tasks

### ISSUE THREAD

**Issue by mpapirkovskyy** [unbroken-dome/gradle-helm-plugin#21]
I'm trying to split project build and only build helm charts when required.
It seems to be easy to build helm charts separately using helmPackage/helmPublish tasks.

But I didn't find easy way to disable helm tasks / build everything but helm charts.

Any advice?

**Comment by tkrullmann** [comment]
Hi,
since the plugin declares the Helm charts as artifacts produced by the project, there is no easy way to exclude them when running `gradle assemble` (or `gradle build`, which depends on `assemble`). After all, the very definition of `assemble` is to build all artifacts in the project.

However, the Helm artifacts are declared under separate configurations, while the "default" artifacts are usually put into the `default` configuration. For example, the `java` plugin puts the artifact produced by `jar` into `default`.

You can use the `build<Configuration>` task name pattern to build only the artifacts for a specific configuration. `gradle buildDefault` should do the trick for you, it will only build the default artifacts but not the Helm charts.

If this is not possible for you and you absolutely need to use unqualified `assemble` or `build`, then the only way I see is to move the Helm charts into a separate subproject.
