### ISSUE TITLE
Execution uploadArchives after helmPackage 

### ISSUE THREAD

**Issue by destanyinside** [unbroken-dome/gradle-helm-plugin#61]
Greetings!
When I exec my task uploadArchives(need to upload other dependencies), plugin also exec task helmPackageChartChart. It's create build/helm/charts/chart_name_folder.
Then, I get the error:
```
* What went wrong:
Execution failed for task ':uploadArchives'.
> Could not publish configuration 'archives'
   > Cannot publish a directory (build/helm/charts/chart_name_folder)

```
Any ideas how to fix this?

**Comment by MetallFoX** [comment]
Hi!
It seems that plugin adds chart's dir at runtime to the `configurations.archives` which uploadArchives uses.

As one of solutions you can dofloolowing:

```
doFirst {
uploadArchives {
    doFirst {
        configurations.archives.with {
            artifacts.removeAll{ it.getFile().isDirectory() }
        }
    }
}
```

But it would be much clearer to add cleanup hook to one of this plugin's tasks.

**Comment by tkrullmann** [comment]
Hi!

I've never really used `uploadArchives` or the `archives` configuration, they are something of a relic of very early Gradle versions. It seems that the `base` plugin adds the artifacts of _every_ configuration that has `isVisible=true` (meaning its artifacts may be resolved by other projects) to `archives`. There is nothing I can do to prevent this, since the visibility is needed for other projects to resolve the chart -- for example, when using the chart dependencies feature.

Admittedly, the use of a directory `File` for the Helm chart artifact path is a bit of a nonstandard use, but then again, that directory is what constitutes the Helm chart if it is not compressed.

Given that use of `archives` and `uploadArchives` is now [deprecated](https://docs.gradle.org/current/userguide/upgrading_version_6.html#using_default_and_archives_configurations), I won't spend too much time trying to make this work. Here are some things I would recommend, as alternatives / in addition to what @MetallFoX suggested:

- convert your scripts to use the newer publication mechanism if possible
- use `uploadDefault` instead of `uploadArchives`. The `default` configuration is probably more what you'd expect, `archives` is a bit misleading as it really will contain _all_ artifacts produced by the project. `default` will contain your JAR but not the Helm chart artifacts.

Even with the workaround as suggested, you would still end up uploading the _packaged_ chart (.tgz file), which is also declared as an artifact by the plugin. You probably won't want all those artifacts published to the same location anyway.
