### ISSUE TITLE
Filter value files in helm-releases plugin 

### ISSUE THREAD

**Issue by thony87** [unbroken-dome/gradle-helm-plugin#98]
Hello, 

I just started to use this plugin, which is great by the way. I have created a chart which I would like to use in different subproject as releases for different functionalities. 

Each chart release should have its own `values.yaml` in which I would like to use filtering without redefining a source chart.

So I created a gradle project to be just an implementation of my chart : 

In my `build.gradle`: 
```
helm {
    releases {
        mydatabase {
            from chart(project: ':database', chart: 'mssqldatabase')
            forTarget('ci') {
                valueFiles.from 'mydatabase.yaml'
            }
        }
    }
}
```
The specific `mydatabase.yaml` file:
```
database:
  name: mydatabase
  scripts:
    - '${myDatabaseScriptRepository}/script-${databaseVersion}.sql'
``` 

I would like my two variables `myDatabaseScriptRepository` and `databaseVersion` (defined in `gradle.properties`) to be replaced by their values but when I install my release with  `gradlew helmInstallToCi -PdatabaseVersion=19.0.778`,  the values are not replaced.

Do you know if their is a way with the plugin to use filtering on a release value file ? 

Thank you.

**Comment by tkrullmann** [comment]
Hi @thony87, and sorry for the late response!

The filtering that is done by the plugin only applies to building charts. Release values files are not filtered; values that depend on Gradle scripting can be set individually with the `values` property instead.

I could imagine a few different solutions here:

1. Use `values` directly, instead of `valueFiles`. This might be the easiest solution unless you have a lot of other stuff to be filtered in your YAML file

```groovy
helm {
    releases {
        mydatabase {
            from chart(project: ':database', chart: 'mssqldatabase')
            forTarget('ci') {
                values.from 'mydatabase.yaml'     // and remove the variable stuff from the YAML file
                values.put('database.scripts', "{${myDatabaseScriptRepository}/script-${databaseVersion}.sql}")
            }
        }
    }
}
```

The `{ }` syntax for the value is required because we're setting a list property.

2. Add a separate `Copy` task and let Gradle do the filtering. Then use the filtered file as input to the Helm release. You can use the `expand` method on a `CopySpec` to resolve `${...}` expressions in files.

```groovy

task filterDatabaseValuesFile(type: Copy) {
    from 'mydatabase.yaml'
    destinationDir = file("$buildDir/database-helm-values")   // or whatever
    expand project.properties
}

helm {
    releases {
        mydatabase {
            from chart(project: ':database', chart: 'mssqldatabase')
            forTarget('ci') {
                installDependsOn filterDatabaseValuesFile

                // add all YAML files from the copy task output dir
                valueFiles.from fileTree(filterDatabaseValuesFile.destinationDir)
            }
        }
    }
}
```

If you need this behavior in multiple projects, you could also add this to a `subprojects` clause in a common parent project:

```groovy
subprojects {
    plugins.withId('org.unbroken-dome.helm-releases') {
        // insert the stuff from above
    }
}
```


Tip: I'd recommend avoiding lists in Helm chart values; they make it harder and less predictable to merge values from different sources. If there's any key that makes sense, try using a map/object structure instead.

**Comment by thony87** [comment]
Hello @tkrullmann, thanks for the reply, I'll use one of the solutions you provided.
