### ISSUE TITLE
helmInstall command doesn't work after pending-install failure state (helm 3.3.4)

### ISSUE THREAD

**Issue by Woxis17** [unbroken-dome/gradle-helm-plugin#99]
When deployment fails to install due to failing job with release status pending-install helmInstall (upgrade) stop working because plugin try to upgrade non existing deployment (not installed successfully but it doesn't remove it with helmDelete)

> Task :abc-package:helmInstallAbcPackageProjectNameToDefault FAILED
> history.go:53: [debug] getting history for release abc-package-project-name
> upgrade.go:121: [debug] preparing upgrade for abc-package-project-name
> Error: UPGRADE FAILED: "abc-package-project-name" has no deployed releases
> helm.go:94: [debug] "abc-package-project-name" has no deployed releases 
> UPGRADE FAILED

Plugin version:
org.unbroken-dome.gradle-plugins.helm:gradle-helm-plugin:1.3.0
helm version: 3.3.4

Possible solution could be extending getRelease method with --all flag when using ls

**Comment by tkrullmann** [comment]
Hi,

you're right, `helm ls --all` should do the trick here.

**Comment by tkrullmann** [comment]
After a bit of trying, I found this is not so simple after all.

If I do `helm ls --all` and find the release in `pending-install` status, and then decide to do a `helm install --replace` instead of `helm upgrade`, then I will get a different error:

    cannot re-use a name that is still in use

So, I suppose the only way the plugin could act here to resolve this would be to do a `helm uninstall` on a pending release first. But this is problematic for various reasons:

- there is no way to tell whether a pending-install release is really stuck or if it's just taking a long time, so just uninstalling it might be too intrusive
- it requires the stuck hook job to have a `hook-delete-policy: before-hook-creation`, otherwise the next install/upgrade will also fail because the job still exists

In general, I'm not aiming to enhance or "fix" the behavior of Helm itself in this plugin. The current logic of choosing `helm install --replace` or `helm install --upgrade` is just for convenience so we don't need different task types for it. Also, it seems that the behavior of `helm upgrade` has been improved in Helm 3.3 so we won't need this distinction anymore.

-> this seems to be a problem with Helm itself, please consider filing an issue there.
